### ISSUE TITLE
'ScriptInit' callback not called if script loaded via "loadjs" rcon command

### ISSUE THREAD

**Issue by andievandy** [damospiderman/samp.js#45]
v0.1.9.6 on SAMP 0.3.7 R2-1 running on Windows 10

as the title says. It works fine on scripts that loaded via "jsfiles" on "server.cfg".

and (actually don't know how to explain this) when startup, in v0.1.9.6 the module from all those scripts are loaded first then the scripts themselves:

```

[19:58:34] [samp.js] v8 Engine version 4.3.61.23 loaded.
[19:58:34] [samp.js] MySQL library version 6.1.6 loaded.
[19:58:34] [samp.js] Loading Module: Utils
[19:58:34] [samp.js] Loading Module: Timers
[19:58:34] [samp.js] Loading Module: Events
[19:58:34] [samp.js] Loading Module: Players
[19:58:34] [samp.js] Loading Module: FileSystem
[19:58:34] [samp.js] Loading Module: Sockets
[19:58:34] [samp.js] Loading Module: HTTP
[19:58:34] [samp.js] Loading Module: MySQL
[19:58:34] [samp.js] Loading Module: Server
[19:58:34] [samp.js] Loading Module: Utils
[19:58:34] [samp.js] Loading Module: Timers
[19:58:34] [samp.js] Loading Module: Events
[19:58:34] [samp.js] Loading Module: Players
[19:58:34] [samp.js] Loading Module: FileSystem
[19:58:34] [samp.js] Loading Module: Sockets
[19:58:34] [samp.js] Loading Module: HTTP
[19:58:34] [samp.js] Loading Module: MySQL
[19:58:34] [samp.js] Loading Module: Server
[19:58:34] [samp.js] Loading Module: Utils
[19:58:34] [samp.js] Loading Module: Timers
[19:58:34] [samp.js] Loading Module: Events
[19:58:34] [samp.js] Loading Module: Players
[19:58:34] [samp.js] Loading Module: FileSystem
[19:58:34] [samp.js] Loading Module: Sockets
[19:58:34] [samp.js] Loading Module: HTTP
[19:58:34] [samp.js] Loading Module: MySQL
[19:58:34] [samp.js] Loading Module: Server
[19:58:34] 
----------------------------------
[19:58:34]  LVDM by Jax
[19:58:34]  Rewritten to samp.js
[19:58:34] ----------------------------------

[19:58:34] 
----------------------------------
[19:58:34]  Real Time System loaded
[19:58:34] ----------------------------------

[19:58:34] 
----------------------------------
[19:58:34]  test
[19:58:34] ----------------------------------
```

in v0.1.9.5 and earlier modules on other scripts are loaded after 1 script finished to load:

```

[21:11:02] [samp.js] v8 Engine version 4.3.61.23 loaded.
[21:11:02] [samp.js] MySQL library version 6.1.6 loaded.
[21:11:02] [samp.js] Loading Module: Utils
[21:11:02] [samp.js] Loading Module: Timers
[21:11:02] [samp.js] Loading Module: Events
[21:11:02] [samp.js] Loading Module: Players
[21:11:02] [samp.js] Loading Module: FileSystem
[21:11:02] [samp.js] Loading Module: Sockets
[21:11:02] [samp.js] Loading Module: HTTP
[21:11:02] [samp.js] Loading Module: MySQL
[21:11:02] [samp.js] Loading Module: Server
[21:11:02] 
----------------------------------
[21:11:02]  LVDM by Jax
[21:11:02]  Rewritten to samp.js
[21:11:02] ----------------------------------

[21:11:02] [samp.js] Loading Module: Utils
[21:11:02] [samp.js] Loading Module: Timers
[21:11:02] [samp.js] Loading Module: Events
[21:11:02] [samp.js] Loading Module: Players
[21:11:02] [samp.js] Loading Module: FileSystem
[21:11:02] [samp.js] Loading Module: Sockets
[21:11:02] [samp.js] Loading Module: HTTP
[21:11:02] [samp.js] Loading Module: MySQL
[21:11:02] [samp.js] Loading Module: Server
[21:11:02] 
----------------------------------
[21:11:02]  test
[21:11:03] ----------------------------------

[21:11:03] [samp.js] Loading Module: Utils
[21:11:03] [samp.js] Loading Module: Timers
[21:11:03] [samp.js] Loading Module: Events
[21:11:03] [samp.js] Loading Module: Players
[21:11:03] [samp.js] Loading Module: FileSystem
[21:11:03] [samp.js] Loading Module: Sockets
[21:11:03] [samp.js] Loading Module: HTTP
[21:11:03] [samp.js] Loading Module: MySQL
[21:11:03] [samp.js] Loading Module: Server
[21:11:03] 
----------------------------------
[21:11:03]  Real Time System loaded
[21:11:03] ----------------------------------
```

here's my "jsfiles":
`jsfiles gamemode.js test.js realtime.js`
is it normal?

**Comment by damopewpew** [comment]
Yeah I changed some things around but forgot to add the ScriptInit call on loadjs. Thanks, I will push an update. I might remove the module logs too

**Comment by andievandy** [comment]
okay then :D

and i just found something..
scripts in "server.cfg" just loaded in alphabetical order instead of which one written first in it
example:
`jsfiles randommessage.js gamemode.js test.js realtime.js`
server just load it like:

```
gamemode.js
randommessage.js
realtime.js
test.js
```

instead of

```
randommessage.js
gamemode.js
test.js
realtime.js
```

**Comment by Crayder** [comment]
Yea the loading order thing, I noticed that. I didn't pay attention enough to see that it was alphabetical, but I noticed it wasn't loading in the order I wanted it to.

**Comment by damopewpew** [comment]
Please use and test this: https://github.com/damospiderman/samp.js/blob/master/bin/samp.js.dll

I've fixed both of those issues and also added a listjs rcon command to list all loaded js files.

**Comment by andievandy** [comment]
now the scripts are loaded in order we wanted, thanks!

but the 'ScriptInit' callback still not getting called when the script loaded via rcon command..

**Comment by damopewpew** [comment]
oh what the hell. I'll check my code when i get home

**Comment by damopewpew** [comment]
Ok this fixes it, https://github.com/damospiderman/samp.js/blob/master/bin/samp.js.dll

**Comment by andievandy** [comment]
All works fine now, thanks again :D

**Comment by andievandy** [comment]
now the server crashes when it tries to load a script that doesn't exists, in previous v0.1.9.6 build it doesn't crash...

**Comment by damopewpew** [comment]
I will look into it lol, i'm sure i fixed that

**Comment by damopewpew** [comment]
Ok fixed and fixed a couple of other things

https://github.com/damospiderman/samp.js/blob/master/bin/samp.js.dll

**Comment by andievandy** [comment]
works fine now, thanks :D
